### ISSUE TITLE
What a bout the connection diagram?

### ISSUE THREAD

**Issue by m4lin** [chidea/pyGPIOclock#1]
Hi

may i ask the connection diagram please.

thanks

**Comment by chidea** [comment]
OK I'll try it, but many 7-segments has their own pin setups and it may be different from my diagram.

**Comment by chidea** [comment]
Never mind.. it looks like any common cathode 7 segments will do the job. Scheme files are on it's way.

**Comment by chidea** [comment]
43bbbe32029c0cff7a4a56656c7d1c6aeaf6fba9

**Comment by m4lin** [comment]
Hi

thanks a lot

I'll have a go, i have already (scavenged) the below one

http://www.lextronic.fr/doc/produit/img1_29610_1384466126.jpg

i'll try to adapt the code/circuit,

thanks again

2016-05-27 0:12 GMT+01:00 chidea notifications@github.com:
